[2024-06-03T07:17:29.398+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alert.run_detect_anomalies_script scheduled__2024-06-02T22:00:00+00:00 [queued]>
[2024-06-03T07:17:29.660+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alert.run_detect_anomalies_script scheduled__2024-06-02T22:00:00+00:00 [queued]>
[2024-06-03T07:17:29.695+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-06-03T07:17:30.241+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_detect_anomalies_script> on 2024-06-02 22:00:00+00:00
[2024-06-03T07:17:30.326+0000] {standard_task_runner.py:60} INFO - Started process 1928 to run task
[2024-06-03T07:17:30.691+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'alert', 'run_detect_anomalies_script', 'scheduled__2024-06-02T22:00:00+00:00', '--job-id', '778', '--raw', '--subdir', 'DAGS_FOLDER/alert.py', '--cfg-path', '/tmp/tmpx6ygjqe2']
[2024-06-03T07:17:31.028+0000] {standard_task_runner.py:88} INFO - Job 778: Subtask run_detect_anomalies_script
[2024-06-03T07:17:33.517+0000] {task_command.py:423} INFO - Running <TaskInstance: alert.run_detect_anomalies_script scheduled__2024-06-02T22:00:00+00:00 [running]> on host cce95859c81a
[2024-06-03T07:17:36.032+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='alert' AIRFLOW_CTX_TASK_ID='run_detect_anomalies_script' AIRFLOW_CTX_EXECUTION_DATE='2024-06-02T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-02T22:00:00+00:00'
[2024-06-03T07:17:36.786+0000] {logging_mixin.py:188} INFO - python: can't open file '/opt/***/network_model/anomaly_trigger.py': [Errno 2] No such file or directory
[2024-06-03T07:17:36.902+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-06-03T07:17:36.961+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=alert, task_id=run_detect_anomalies_script, execution_date=20240602T220000, start_date=20240603T071729, end_date=20240603T071736
[2024-06-03T07:17:37.205+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-06-03T07:17:37.594+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
