[2024-06-01T03:55:17.079+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_bigquery_2.check_file_exists manual__2024-06-01T03:55:04.359613+00:00 [queued]>
[2024-06-01T03:55:17.129+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_bigquery_2.check_file_exists manual__2024-06-01T03:55:04.359613+00:00 [queued]>
[2024-06-01T03:55:17.132+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-06-01T03:55:17.187+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): check_file_exists> on 2024-06-01 03:55:04.359613+00:00
[2024-06-01T03:55:17.220+0000] {standard_task_runner.py:60} INFO - Started process 4221 to run task
[2024-06-01T03:55:17.226+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'csv_to_bigquery_2', 'check_file_exists', 'manual__2024-06-01T03:55:04.359613+00:00', '--job-id', '449', '--raw', '--subdir', 'DAGS_FOLDER/csv_to_bigquery_2.py', '--cfg-path', '/tmp/tmp5tuep3qb']
[2024-06-01T03:55:17.234+0000] {standard_task_runner.py:88} INFO - Job 449: Subtask check_file_exists
[2024-06-01T03:55:17.520+0000] {task_command.py:423} INFO - Running <TaskInstance: csv_to_bigquery_2.check_file_exists manual__2024-06-01T03:55:04.359613+00:00 [running]> on host 6204b7e2d2f9
[2024-06-01T03:55:18.436+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_bigquery_2' AIRFLOW_CTX_TASK_ID='check_file_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T03:55:04.359613+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T03:55:04.359613+00:00'
[2024-06-01T03:55:18.551+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-01T03:55:18.597+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-01T03:55:18.607+0000] {gcs.py:249} INFO - Getting list of the files. Bucket: testing_bucket_df12; Delimiter: None; Prefix(es): network_data/hello_1.csv
[2024-06-01T03:55:23.730+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-06-01T03:55:23.775+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=csv_to_bigquery_2, task_id=check_file_exists, execution_date=20240601T035504, start_date=20240601T035517, end_date=20240601T035523
[2024-06-01T03:55:23.903+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-06-01T03:55:24.065+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
