[2024-06-03T07:56:46.437+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alert.detect_and_alert manual__2024-06-03T07:56:44.316929+00:00 [queued]>
[2024-06-03T07:56:46.452+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alert.detect_and_alert manual__2024-06-03T07:56:44.316929+00:00 [queued]>
[2024-06-03T07:56:46.453+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-06-03T07:56:46.475+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): detect_and_alert> on 2024-06-03 07:56:44.316929+00:00
[2024-06-03T07:56:46.481+0000] {standard_task_runner.py:60} INFO - Started process 7966 to run task
[2024-06-03T07:56:46.484+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'alert', 'detect_and_alert', 'manual__2024-06-03T07:56:44.316929+00:00', '--job-id', '808', '--raw', '--subdir', 'DAGS_FOLDER/alert.py', '--cfg-path', '/tmp/tmp0dw4nbum']
[2024-06-03T07:56:46.487+0000] {standard_task_runner.py:88} INFO - Job 808: Subtask detect_and_alert
[2024-06-03T07:56:46.545+0000] {task_command.py:423} INFO - Running <TaskInstance: alert.detect_and_alert manual__2024-06-03T07:56:44.316929+00:00 [running]> on host cce95859c81a
[2024-06-03T07:56:46.660+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='alert' AIRFLOW_CTX_TASK_ID='detect_and_alert' AIRFLOW_CTX_EXECUTION_DATE='2024-06-03T07:56:44.316929+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-03T07:56:44.316929+00:00'
[2024-06-03T07:56:48.256+0000] {logging_mixin.py:188} INFO - Traceback (most recent call last):
  File "/opt/***/dags/network_model/anomaly_trigger.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2024-06-03T07:56:48.339+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-06-03T07:56:48.354+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=alert, task_id=detect_and_alert, execution_date=20240603T075644, start_date=20240603T075646, end_date=20240603T075648
[2024-06-03T07:56:48.388+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-06-03T07:56:48.426+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
