[2024-06-03T13:22:18.818+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: alert.detect_and_alert manual__2024-06-03T13:22:15.283692+00:00 [queued]>
[2024-06-03T13:22:18.848+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: alert.detect_and_alert manual__2024-06-03T13:22:15.283692+00:00 [queued]>
[2024-06-03T13:22:18.849+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-06-03T13:22:18.893+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): detect_and_alert> on 2024-06-03 13:22:15.283692+00:00
[2024-06-03T13:22:18.903+0000] {standard_task_runner.py:60} INFO - Started process 3379 to run task
[2024-06-03T13:22:18.909+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'alert', 'detect_and_alert', 'manual__2024-06-03T13:22:15.283692+00:00', '--job-id', '851', '--raw', '--subdir', 'DAGS_FOLDER/alert.py', '--cfg-path', '/tmp/tmpuy9qyah5']
[2024-06-03T13:22:18.914+0000] {standard_task_runner.py:88} INFO - Job 851: Subtask detect_and_alert
[2024-06-03T13:22:19.013+0000] {task_command.py:423} INFO - Running <TaskInstance: alert.detect_and_alert manual__2024-06-03T13:22:15.283692+00:00 [running]> on host 0a54be82eb52
[2024-06-03T13:22:19.184+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='alert' AIRFLOW_CTX_TASK_ID='detect_and_alert' AIRFLOW_CTX_EXECUTION_DATE='2024-06-03T13:22:15.283692+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-03T13:22:15.283692+00:00'
[2024-06-03T13:22:21.272+0000] {logging_mixin.py:188} INFO - Traceback (most recent call last):
  File "/opt/***/dags/network_model/anomaly_trigger.py", line 4, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2024-06-03T13:22:21.310+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-06-03T13:22:21.324+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=alert, task_id=detect_and_alert, execution_date=20240603T132215, start_date=20240603T132218, end_date=20240603T132221
[2024-06-03T13:22:21.388+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-06-03T13:22:21.418+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
